- hosts: webservers
  gather_facts: no
  vars:
    users:
      - jaime
      - sansa
      - robert

  tasks:

    - name: update apt cache
      ansible.builtin.apt:
        update_cache: yes
      become: yes
      tags: cache

    - name: install git
      ansible.builtin.apt:
        name: git
        state: present
      become: yes
      tags: install

    - name: add users
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
        groups: malcom
      loop: "{{ users }}"
      become: yes

    - name: add git config
      ansible.builtin.template:
        src: templates/.gitconfig.j2
        dest: "/home/{{ item }}/.gitconfig"
      loop: "{{ users }}"
      become: yes
